services:
  postgres:
    container_name: "postgres"
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-S3cr_t}
      - POSTGRES_DB=${DATABASE_NAME:-INKECOEX_Webshop}

volumes:
  postgres-data:
